# Generated by Django 3.1.14 on 2022-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220214_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='scholar_credit',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], max_length=50),
        ),
    ]
