# Generated by Django 3.1.14 on 2022-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_student_data_scholar_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='scholar_credit_ammount',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], max_length=50),
        ),
    ]
