# Generated by Django 3.1.14 on 2022-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student_data_scholar_credit_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='scholar_credit_ammount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
