# Generated by Django 3.1.14 on 2022-02-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220214_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='scholar_credit',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=50),
        ),
    ]
