# Generated by Django 3.1.14 on 2022-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_student_data_refrenced_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='installment_1_ammount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_2_ammount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_3_ammount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_4_ammount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_5_ammount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='installment_5_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
