# Generated by Django 3.1.14 on 2022-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20220215_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='installment_1_ammount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_2_ammount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_3_ammount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_4_ammount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_5_ammount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='scholar_credit_ammount',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
