# Generated by Django 3.1.14 on 2022-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20220215_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='number_of_installment',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True),
        ),
    ]
