# Generated by Django 3.1.14 on 2022-02-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20220216_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='department',
            field=models.CharField(blank=True, choices=[('MBA department', 'MBA department'), ('Computer Science department', ' Computer Science department'), ('Electrical department', 'Electrical department'), ('Mechanical Department', 'Mechanical Department'), ('Civil Department', 'Civil Department'), ('Electronic and Engineering Department', 'Electronic and Engineering Department')], max_length=50, null=True),
        ),
    ]
